version: '3.8'

services:
  gto_backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - gto_mongo

  gto_frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  gto_mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  gto_nginx:
    image: nginx:latest
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gto_frontend
      - gto_backend

volumes:
  mongo-data:
