version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  frontend:
    container_name: G.T.O_Frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    container_name: G.T.O_Backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mygame
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    container_name: G.T.O_Mongo
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
