FROM node:20.15.0

WORKDIR /app

COPY backend/package.json backend/package-lock.json ./
RUN npm install
RUN npm install -g nodemon

COPY backend/ ./

EXPOSE 5000

CMD ["nodemon", "server.js"]
